ecomapp/urls.py
from django.urls import path
from .views import *


app_name = "ecomapp"
urlpatterns = [

    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),
#     path("sellerform/", index, name="sellerform"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),

     path("seller/", SellerView.as_view(), name="seller"),
     path("lease/", LeaseView.as_view(), name="lease"),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    full_title = models.CharField(max_length=200, default="")
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    contact_number = models.CharField(max_length=200, default="")
    contact_email = models.CharField(max_length=200, default="")
    available_for_lease = models.CharField(max_length=300, null=True, blank=True)
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("UPI","UPI")
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)
    
class Lease(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    address = models.TextField()
    phone_number = models.CharField(max_length=200)
    secondary_number = models.CharField(max_length=200)
    date = models.CharField(max_length=200)
    # gender = models.CharField(max_length=200)
    # employment
    current_designation = models.CharField(max_length=200)
    monthly_salary = models.CharField(max_length=200)
    address_of_residence = models.TextField()
    landlord_name = models.CharField(max_length=200)
    duration_lived_in_this_residence = models.CharField(max_length=200)
    # evicted = models.CharField(max_length=200)
    # pets
    # felony
    # bankruptcy
    explanation = models.TextField()
    required_lease_time = models.CharField(max_length=200, default="")

    def __str__(self):
        return "Name: " + str(self.name)

    

ecomapp/forms.py
from django import forms
from .models import Order, Customer, Product, Lease
from django.contrib.auth.models import User
from django.forms import TextInput, PasswordInput, EmailInput


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by", "shipping_address",
                  "mobile", "email", "payment_method"]


class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())

    class Meta:
        model = Customer
        fields = ["username", "password", "email", "full_name", "address"]

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError(
                "Customer with this username already exists.")

        return uname


class CustomerLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())


class ProductForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
        "class": "form-control",
        "multiple": True
    }))

    class Meta:
        model = Product
        fields = ["title", "slug", "category", "image", "marked_price",
                  "selling_price", "description", "warranty", "return_policy"]
        widgets = {
            "title": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product title here..."
            }),
            "slug": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the unique slug here..."
            }),
            "category": forms.Select(attrs={
                "class": "form-control"
            }),
            "image": forms.ClearableFileInput(attrs={
                "class": "form-control"
            }),
            "marked_price": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Marked price of the product..."
            }),
            "selling_price": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Selling price of the product..."
            }),
            "description": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Description of the product...",
                "rows": 5
            }),
            "warranty": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product warranty here..."
            }),
            "return_policy": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product return policy here..."
            }),

        }


class PasswordForgotForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Enter the email used in customer account..."
    }))

    def clean_email(self):
        e = self.cleaned_data.get("email")
        if Customer.objects.filter(user__email=e).exists():
            pass
        else:
            raise forms.ValidationError(
                "Customer with this account does not exists..")
        return e


class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Enter New Password',
    }), label="New Password")
    confirm_new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Confirm New Password',
    }), label="Confirm New Password")

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get("new_password")
        confirm_new_password = self.cleaned_data.get("confirm_new_password")
        if new_password != confirm_new_password:
            raise forms.ValidationError(
                "New Passwords did not match!")
        return confirm_new_password
    
class SellerForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=["title","full_title","slug","category","image","marked_price", "selling_price", "description", "contact_number", "contact_email", "available_for_lease", "warranty", "return_policy", "view_count"]

class LeaseForm(forms.ModelForm):
    class Meta:
        model=Lease
        fields=["name", "email", "address", "phone_number", "secondary_number", "date", "current_designation", "monthly_salary", "address_of_residence", "landlord_name", "duration_lived_in_this_residence", "explanation", "required_lease_time"]
        

templates/addtocart.html
{% extends 'base.html' %}

{% block title %}Add to cart{% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.lordicon.com/bhenfmcm.js"></script>
    <script src="https://cdn.lordicon.com/bhenfmcm.js"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg" id="top-bar">
        <a class="navbar-brand" href="{% url 'ecomapp:home' %}">
            <img src = "/media/logo-no-background.png" height="43vh" width="83.8vw">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active" id="nav-bar-items">
                <a class="nav-link" href="{% url 'ecomapp:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active" id="nav-bar-items" >
                <a class="nav-link" href="{% url 'ecomapp:allproducts' %}">All Products</a>
            </li>
            {% if request.user.customer %}
            <li class="nav-item active" id="nav-bar-items">
                <a class="nav-link" href="{% url 'ecomapp:seller' %}">Sell</a>
            </li>
            {% else %}
            <li class="nav-item active" id="nav-bar-items">
                <a class="nav-link" href="">Sell</a>
            </li>
            {% endif %}
            <li class="search-bar" id="nav-bar-items">
                <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
                    <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
                    <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </li>
            
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ecomapp:mycart' %}">
                    <lord-icon
                        src="https://cdn.lordicon.com/cllunfud.json"
                        trigger="hover"
                        colors="outline:#121331,primary:#646e78,secondary:#b2dbee"
                        style="width:40px;height:40px">
                    </lord-icon></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <lord-icon
                        src="https://cdn.lordicon.com/dqxvvqzi.json"
                        trigger="hover"
                        colors="outline:#121331,primary:#f4c89c,secondary:#b2dbee"
                        state="hover-nodding"
                        style="width:40px;height:40px">
                    </lord-icon>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if request.user.customer %}
                    <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">My Profile</a>
                    <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Logout</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Register</a>
                    <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Login</a>
                    {% endif %}
                
                </div>
            </li>
            </ul>
            </form>
        </div>
        </nav>
    <hr>

    {% block content %}
    {% endblock %}

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nunito&display=swap');
        body{
            font-family: 'Nunito', sans-serif;
            font-weight: bold;
            font-size: 19px;
        }
        #top-bar{
            background-color: #3FA7D6;
        }
        #nav-bar-items{
            padding-top:2vh;
        }
        .nav-link{
            color: white;
        }
        .navbar-link{
            color: white;
        }
        .nav-link:hover{
            color: #27187E;
        }
        .form-control{
            background-color: #e0e0e0;
        }
        .btn{
            background-color: #757761;
            border-color: #757761;
        }
        .btn:hover{
            background-color: #707070;
            border-color: #707070;
            transform: scale(1.05);
            transition: 300ms;
        }

        .search-bar{
            padding-left: 2vw;
            padding-right: 35vw;
        }
    </style>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>

templates/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'ecomapp:mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Place order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/contactus.html
{% extends 'base.html' %}

{% block title %}Contact us{% endblock %}

{% block content %}
    <h1>To Contact us, Call the following numbers</h1>
    <p>989898989898</p>
    <p>989898989898</p>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}

{% block title %}Customer Registration{% endblock %}

{% block content %}
<style>
    .errorlist{
        color: red;
    }
    
    .grid-box{
        display: grid;
        grid-template-columns: 0.5fr 1.5fr;
        grid-gap: 3vh;
    }

    #id_username, #id_password, #id_email, #id_full_name, #id_address{
        background-color: #e0e0e0;
        border: 2px #c9c9c9 solid;
        border-radius: 15px;
        padding: 2px;
    }
    #id_username:hover, #id_password:hover, #id_email:hover, #id_full_name:hover, #id_address:hover{
        background-color: #d6d3d3;
    }

    #id_username:focus, #id_password:focus, #id_email:focus, #id_full_name:focus, #id_address:focus{
        outline: 2px #d6d3d3 solid;
    }
    
    .icon{
        display: flex;
        justify-content: center;
    }
    
</style>
<script src="https://cdn.lordicon.com/bhenfmcm.js"></script>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <!-- <h3><center>Customer Registration Form</center></h3><hr> -->
            <div class="icon">
                <lord-icon
                    src="https://cdn.lordicon.com/dxjqoygy.json"
                    trigger="loop"
                    delay="1000"
                    colors="primary:#3fa7d6,secondary:#707070"
                    style="width:250px;height:250px">
                </lord-icon>
            </div>
            <form action="" method="POST" autocomplete="off">
                {% csrf_token %}
                <div class="grid-box">
                    <label for="id_username">Username</label>
                    {{form.username}}
                    <label for="id_password">Password</label>
                    {{form.password}}
                    <label for="id_email">Email</label>
                    {{form.email}}
                    <label for="id_full_name">Full Name</label>
                    {{form.full_name}}
                    <label for="id_address">Address</label>
                    {{form.address}}
                </div>
                <br>
                <center><button class="btn btn-dark">Register as a Customer</button></center>
            </form>
            <br>
            <center><p> Already have an account? <a href="{% url 'ecomapp:customerlogin' %}">Login here</a></p></center>
        </div>
    </div>
</div>
{% endblock %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %} My cart{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SNo.</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'ecomapp:emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'ecomapp:checkout' %}"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/productdetail.html
{% extends 'base.html' %}

{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container">
    <h3>Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-4">
            <img src="{{product.image.url}}" alt="" class="img-fluid">
            <div class="row">
                {% for pi in product.productimage_set.all %}
                <div class="col-md-4 p-3">
                    <a href="{{pi.image.url}}" target="_blank">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <h4>{{product.full_title}} (Viewed {{product.view_count}} times)</h4>
            <hr>
            <h5><b>Category:</b> {{product.category}}</h5>
            <h5>Price: Rs. {{product.selling_price}}</h5>
            <!-- <strike>Rs. {{product.marked_price}}</strike>  -->
            <a href="{% url 'ecomapp:addtocart' product.id %}" class="btn btn-dark">Add To Cart</a>
            {% if product.available_for_lease == "yes" %}
            <a href="{% url 'ecomapp:lease' %}" class="btn btn-dark">Lease</a>
            {% endif %}
            <hr>
            <p class="text">Warranty: <b>{{product.warranty}} years</b></p>
            <hr>
            <p class="text">Return Policy: <b>{{product.return_policy}}</b></p>
            <hr>
            <p class="text">Lease Availability: <b>{{product.available_for_lease}}</b></p>
            <hr>
            <p>{{product.description}}</p>
            <hr>
            <p><b>Contact Number:</b> {{product.contact_number}}</p>
            <hr>
            <p><b>Contact Email:</b> {{product.contact_email}}</p>
        </div>
    </div>

</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block title %}Search {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-3">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-9">
                    <h4><a href="{% url 'ecomapp:productdetail' result.slug %}" style="color:#4F413E">{{result.title}}</a></h4>
                    <p>{{result.description|truncatewords:50}}</p>
                    <p>Return Policy: {{result.return_policy}}</p>
                    <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-dark">Add To Cart</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/seller.html
{% extends 'base.html' %}

{% block title %}Seller{% endblock %}

{% block content %}
<style>
        .errorlist {
        color: red;
    }

    .grid-box{
        display: grid;
        grid-template-columns: 0.5fr 1.5fr;
        grid-gap: 3vh;
    }

    #id_title, #id_full_title, #id_slug,#id_category,#id_image,#id_marked_price, #id_selling_price, #id_description, #id_contact_number, #id_contact_email, #id_available_for_lease, #id_warranty, #id_return_policy, #id_view_count{
        background-color: #e0e0e0;
        border: 2px #c9c9c9 solid;
        border-radius: 15px;
        padding: 2px;
    }
    #id_username:hover, #id_password:hover, #id_email:hover, #id_full_name:hover, #id_address:hover{
        background-color: #d6d3d3;
    }

    #id_username:focus, #id_password:focus, #id_email:focus, #id_full_name:focus, #id_address:focus{
        outline: 2px #d6d3d3 solid;
    }

    .icon{
        display: flex;
        justify-content: center;
    }

</style>
<!-- <script src="https://cdn.lordicon.com/bhenfmcm.js"></script> -->
<center><h1>Seller Form</h1></center>
<hr>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <!-- <center><h3>Customer Login Form</h3></center> -->
            <!-- <hr> -->
            <form action="" method="POST" autocomplete="off">
                {% csrf_token %}
                <div class="grid-box">
                    <label for="id_title">Title</label>
                    {{form.title}}
                    <label for="id_full_title">Full Title</label>
                    {{form.full_title}}
                    <label for="id_slug">Slug</label>
                    {{form.slug}}
                    <label for="id_category">Category</label>
                    {{form.category}}
                    <label for="id_image">Image</label>
                    {{form.image}}
                    <label for="id_marked_price">Marked Price</label>
                    {{form.marked_price}}
                    <label for="id_selling_price">Selling Price</label>
                    {{form.selling_price}}
                    <label for="id_description">Description</label>
                    {{form.description}}
                    <label for="id_contact_number">Contact Number</label>
                    {{form.contact_number}}
                    <label for="id_contact_email">Contact Email</label>
                    {{form.contact_email}}
                    <label for="id_available_for_lease">Lease Availability (yes/no)</label>
                    {{form.available_for_lease}}
                    <label for="id_warranty">Warranty</label>
                    {{form.warranty}}
                    <label for="id_return_policy">Return Policy</label>
                    {{form.return_policy}}
                    <label for="id_view_count">View count</label>
                    {{form.view_count}}
                </div>
                <br>
                <center>
                    <button class="btn btn-dark">Submit</button>
                    {% if error %}
                    <br>
                    <li style="color: red;">{{error}}</li>
                    {% endif %}
                </center>
            </form>
            <br>
            <center><p>Forgot Password?<a href="{% url 'ecomapp:passworforgot' %}">Reset now.</a></p></center>
            <center><p> Or Don't Have an Account? <a href="{% url 'ecomapp:customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here</a></p></center>
            <br>
        </div>
    </div>
</div>
{% endblock %}